export type View = "workflow"|"passports"|"handoffs"|"conflicts"|"audit";
export type Decision = "keep-8"|"change-10"|"revise"|"recheck"|"stop";
export interface Passport { id:string; name:string; organization:string; role:string; capabilities:string[]; allowedData:string[]; restrictedData:string[]; canModify:string[]; mustNotModify:string[]; approvalRequired:string[]; }
export interface Handoff { id:string; fromAgent:string; toAgent:string; task:string; goal:string; output:string; evidence:string[]; assumptions:string[]; mustKeep:string[]; canChange:string[]; completionCriteria:string[]; openQuestions:string[]; receiverUnderstanding:string[]; receiverNeedsConfirmation:string[]; createdAt:string; }
export interface Conflict { id:string; type:string; severity:string; field:string; sourceValue:string; proposedValue:string; evidence:string[]; violatedRule:string; permissionCheck:string; approver:string; status:string; ruleChecks?:{rule:string;status:string;detail:string}[]; }
export interface AuditEvent { id:string; at:string; actor:string; type:string; title:string; detail:string; }
export interface Run { id:string; projectId:string; status:"awaiting-approval"|"completed"|"revision-requested"; currentAgent:string; verdict:"GO"|"REVISE"|"STOP"; passports:Passport[]; handoffs:Handoff[]; conflicts:Conflict[]; audit:AuditEvent[]; approval?:{decision:Decision;reason:string;approver:string;decidedAt:string}; finalResult?:string; }
export interface Project { id:string; name:string; goal:string; country:string; organization:string; finalApprover:string; createdAt:string; }

export const passportSeed:Passport[]=[
 {id:"manager",name:"Manager Agent",organization:"Bridge X",role:"프로젝트 목표를 업무로 분배하고 승인 게이트를 관리",capabilities:["planning","delegation","decision routing"],allowedData:["project brief","agent outputs"],restrictedData:["customer personal data"],canModify:["task assignment","workflow order"],mustNotModify:["core curriculum"],approvalRequired:["scope change"]},
 {id:"curriculum",name:"Specialist Agent A",organization:"Project Team",role:"기준 결과와 품질 조건을 관리",capabilities:["domain analysis","quality review"],allowedData:["project brief","approved evidence"],restrictedData:["restricted personal data"],canModify:["draft output","delivery detail"],mustNotModify:["approved scope","human decisions"],approvalRequired:["scope change"]},
 {id:"localization",name:"Specialist Agent B",organization:"Project Team",role:"프로젝트 맥락에 맞게 실행안을 조정",capabilities:["adaptation","context analysis"],allowedData:["project brief","agent handoff"],restrictedData:["restricted personal data"],canModify:["execution detail","proposed change"],mustNotModify:["mustKeep conditions","human decisions"],approvalRequired:["mustKeep change"]},
 {id:"risk",name:"Quality & Risk Agent",organization:"Global Quality",role:"구조화 Handoff의 충돌·권한·완료 조건을 검증",capabilities:["quality review","policy check","audit"],allowedData:["all handoffs","decision ledger"],restrictedData:["raw personal data"],canModify:["risk findings","release recommendation"],mustNotModify:["human decision"],approvalRequired:["risk acceptance"]}
];

export function demoRun(project:Project):Run{
 const at=new Date().toISOString(), ev=(actor:string,type:string,title:string,detail:string):AuditEvent=>({id:crypto.randomUUID(),at,actor,type,title,detail});
 const handoffs:Handoff[]=[
 {id:"HO-001",fromAgent:"Manager Agent",toAgent:"Korea Curriculum Agent",task:"프로젝트 목표를 기준 교육과정 업무로 분배",goal:project.goal,output:`${project.country} 출시를 위한 역할별 작업 순서와 승인 게이트 정의`,evidence:["프로젝트 목표","Agent Passport 권한표"],assumptions:[`${project.organization}이 한국 과정의 학습 품질을 기준선으로 사용`],mustKeep:["프로젝트 2회","수료평가","핵심 교육과정"],canChange:["일정 배치","홍보 문구"],completionCriteria:["8주 기준안과 근거 전달"],openQuestions:["최종 승인자는 누구인가?"],receiverUnderstanding:["프로젝트 목표와 8주 기준을 먼저 보존한다"],receiverNeedsConfirmation:["국가별 운영 제약의 우선순위"],createdAt:at},
 {id:"HO-002",fromAgent:"Korea Curriculum Agent",toAgent:"Vietnam Localization Agent",task:`${project.country} 운영을 위한 8주 AI 교육과정 현지화`,goal:"현지 참여율을 높이면서 핵심 교육 품질 유지",output:"8주 교육과정 초안 — 주 2회, 프로젝트 2회, 8주차 수료평가",evidence:["한국 3개 기수 평균 수료율 87%","8주차 프로젝트 완주율 82%"],assumptions:["평일 저녁 주 2회 참여 가능"],mustKeep:["교육 기간 8주","프로젝트 2회","수료평가"],canChange:["요일·시간","현지 사례","홍보 문구"],completionCriteria:["베트남 운영팀 검토","필수 조건 보존 확인"],openQuestions:["공휴일 2주를 일정 안에서 어떻게 흡수할 것인가?"],receiverUnderstanding:["일정과 마케팅은 현지화하되 8주 계약은 유지한다"],receiverNeedsConfirmation:["기간 변경 승인 여부"],createdAt:at},
 {id:"HO-003",fromAgent:"Vietnam Localization Agent",toAgent:"Quality & Risk Agent",task:"베트남 운영안 리스크 검토",goal:"현지 참여율과 교육 품질 동시 확보",output:"현지 공휴일과 직장인 일정을 반영해 교육 기간을 10주로 변경 제안",evidence:["베트남 공휴일 2주 중첩","현지 운영팀 사전 인터뷰 6건","평일 야간 선호 응답 78%"],assumptions:["주당 학습 부담을 낮추면 이탈률이 감소"],mustKeep:["프로젝트 2회","수료평가"],canChange:["요일·시간","현지 사례","홍보 문구"],completionCriteria:["기간 변경 승인","품질·리스크 검토 완료"],openQuestions:["8주 유지와 10주 변경 중 어떤 결정을 승인할 것인가?"],receiverUnderstanding:["10주 변경은 제안이며 실행 계약이 아니다"],receiverNeedsConfirmation:["course duration 변경 권한과 사람 승인"],createdAt:at}
 ];
 const ruleChecks=[{rule:"숫자·일정 불일치",status:"failed",detail:"기준안과 후속 Agent 제안의 범위가 다름"},{rule:"mustKeep 누락·변경",status:"failed",detail:"필수 조건의 보존 여부를 확인해야 함"},{rule:"권한 없는 변경",status:"approval-required",detail:"Passport상 승인 필요 항목이 포함됨"},{rule:"사람 승인 필요 조건",status:"approval-required",detail:"승인자 결정 전 자동 진행 중단"},{rule:"근거 없는 주장",status:"passed",detail:"프로젝트 목표와 Agent output이 연결됨"},{rule:"완료 조건 누락",status:"needs-review",detail:"수신 Agent의 완료 조건 확인 필요"}];
 return{id:crypto.randomUUID(),projectId:project.id,status:"awaiting-approval",currentAgent:"Human approval",verdict:"STOP",passports:passportSeed,handoffs,conflicts:[{id:"CF-001",type:"범위·권한 충돌",severity:"critical",field:"scope_change",sourceValue:"기준안 유지",proposedValue:`${project.country} 운영 제안`,evidence:["프로젝트 목표","전문 Agent 제안"],violatedRule:"mustKeep 변경 또는 승인 필요 조건은 사람 결정 전 자동 실행할 수 없음",permissionCheck:"approval-required",approver:project.finalApprover,status:"open",ruleChecks}],audit:[ev("System","project.created","프로젝트 생성",`${project.country} · ${project.organization}`),ev("Manager Agent","agent.assigned","전문 에이전트 업무 분배","Curriculum → Localization → Quality & Risk"),ev("Korea Curriculum Agent","handoff.created","기준안 전달","구조화 Handoff와 mustKeep 조건 포함"),ev("Vietnam Localization Agent","change.proposed","운영안 변경 제안","프로젝트 제약과 현지 조건을 근거로 제안"),ev("Policy Engine","conflict.detected","범위 및 권한 충돌 탐지","승인 전 자동 진행 중단"),ev("System","approval.requested",`${project.finalApprover} 승인 요청`,"승인 필요 조건 확인") ]};
}

export function demoDecide(run:Run,decision:Decision,reason:string,approver:string):Run{
 const at=new Date().toISOString(), event=(actor:string,type:string,title:string,detail:string):AuditEvent=>({id:crypto.randomUUID(),at,actor,type,title,detail});
 const approval={decision,reason,approver,decidedAt:at};
 if(decision==="revise"||decision==="recheck")return{...run,approval,status:"revision-requested",verdict:"REVISE",currentAgent:decision==="revise"?"Vietnam Localization Agent":"Project owner",conflicts:run.conflicts.map(c=>({...c,status:"revision-requested"})),audit:[...run.audit,event(approver,"approval.decided",decision==="revise"?"수정 요청":"담당자 재검토 요청",reason),event("Manager Agent","handoff.routed","승인 의견 재전달","다음 담당자의 입력 맥락에 결정과 이유를 포함했습니다.")]};
 if(decision==="stop")return{...run,approval,status:"completed",verdict:"STOP",currentAgent:"사람이 중단",finalResult:"사람의 결정으로 실행을 중단했습니다.",conflicts:run.conflicts.map(c=>({...c,status:"resolved"})),audit:[...run.audit,event(approver,"approval.decided","실행 중단",reason),event("Manager Agent","run.stopped","다음 Agent 실행 중단","중단 이유가 Decision Context와 Audit Log에 기록되었습니다.")]};
 const finalResult=decision==="keep-8"?"기준안을 유지하고 변경 가능한 운영 조건만 조정합니다.":"변경안을 승인하고 필수 조건을 유지한 채 다음 단계로 전달합니다.";
 const last:Handoff={id:"HO-004",fromAgent:"Quality & Risk Agent",toAgent:"Manager Agent",task:"최종 출시안 확정",goal:"승인 결정에 따른 안전한 출시",output:finalResult,evidence:[`Human decision: ${decision}`,reason],assumptions:["승인 조건이 최종 계약에 반영됨"],mustKeep:["프로젝트 2회","수료평가","결정 기록"],canChange:["세부 운영 시간"],completionCriteria:["최종 승인 완료","Audit Log 기록 완료"],openQuestions:["다음 실행에서 확인할 운영 지표"],receiverUnderstanding:["사람의 결정과 이유를 다음 실행 입력으로 사용"],receiverNeedsConfirmation:["없음 — 승인 조건을 기준으로 실행"],createdAt:at};
 return{...run,approval,status:"completed",verdict:"GO",currentAgent:"Completed",finalResult,conflicts:run.conflicts.map(c=>({...c,status:"resolved"})),handoffs:[...run.handoffs,last],audit:[...run.audit,event(approver,"approval.decided",decision==="keep-8"?"8주 유지 승인":"10주 변경 승인",reason),event("Quality & Risk Agent","run.completed","품질·리스크 검토 완료",finalResult),event("Manager Agent","project.completed","최종 결과 확정","다음 실행 단계로 전달 가능한 GO 상태")]};
}
